### PR TITLE
Fix #95 : Add CC to sender for email file sharing

### LINKED ISSUE #95: Add CC to sender for email file sharing
The sender should be able to receive a copy of the email sent to the recipient.

### PR DESCRIPTION
**Pull request by vayan**

### CODE REVIEW

**Comment by remie** [comment]
@vayan : perhaps it's an idea to also add a checkbox in the Email settings page to allow enable/disable of this feature? If not, sys admins will get spammed without being able to control this behaviour :)

**Comment by vayan** [comment]
@remie Yeah you're right ! Doing that :+1:

**Comment by vayan** [comment]
screenshot from 2015-10-05 23 18 12

**Comment by remie** [comment]
Cool stuff! Thanks for also including the UI test

**Pull request merged**
