### PR TITLE
lint: update src folder

### PR DESCRIPTION
**Pull request by Lesterpig**
Same as #130 +

- Remove (carefully!) unused variables
- Check end of files

### CODE REVIEW

**Comment by remie** [comment]
@Lesterpig : unfortunately this will not work out properly. JSHint is now also removing variables which are used to ensure that Browserify includes the package (like var Bootstrap = require('bootstrap')). Is it possible to split this into multiple PR's? One for white spaces and tabs, and the other for variables? That will make it easier to review it.

**Comment by Lesterpig** [comment]
Yep, no problem!

**Comment by remie** [comment]
Thanks!

**Comment by Lesterpig** [comment]
I've updated the PR :)
The only variables removed are `var instance = ...`

Is it ok for you?

**Comment by remie** [comment]
yes, this looks great. Waiting for the CI to finish and will merge afterwards.

**Comment by Lesterpig** [comment]
Great! Thank you for your time ;-)

**Comment by remie** [comment]
Thank you for cleaning up my mess :)

**Pull request merged**
